### ISSUE TITLE
Remove this git repository

### ISSUE THREAD

**Issue by stappersg** [GranderStark/YouTrack-Rest-Python3#1]
The README.md says

> Why does this exists? This package doesn't work for me, just to not completely waste time that I spent on this part of job

Then you wrote https://github.com/GranderStark/Python3-Youtrack-api 

Please remove this git repository to prevent that other people waste time on this repo.

**Comment by GranderStark** [comment]
Hello!

Other people might find this repository useful, unfortunately, new library does not cover all features that one might needed from integration with youtrack (not yet)

I will mark old one as deprecated
